global:
  scrape_interval: 5s
  evaluation_interval: 5s
 
rule_files:


scrape_configs:
  - job_name: 'prometheus'
    
    static_configs:
    - targets: ['127.0.0.1:9090']
  
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['192.168.99.100:8080']
    