global:
  scrape_interval: 5s
  evaluation_interval: 5s
 
rule_files:


scrape_configs:
  - job_name: 'prometheus'
    
    static_configs:
    - targets: ['127.0.0.1:9090']
  
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['192.168.1.4:8080']
    
    
#run this file:    
#docker run -p 9090:9090 -v /Users/lnarcisoov/dev/eclipse-workspace/ms-exp-grafana-prometheus/src/main/resources/prometheus.yml prom/prometheus

#run grafana:
#docker run -d --name=grafana88 -p 3000:3000 grafana/grafana